version: '3.8'

services:
  spell-note-db:
    image: "postgres:16.4-alpine3.20"
    container_name: spell-note-db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty
      - SSLMode=disabled
      - DATABASE_HOST=spell-note-db
    ports:
      - "5432:5432"
    networks:
      - app-network

  migrate:
    image: migrate/migrate
    container_name: migrate
    command: >
      -path=/migrations/ -database postgres://postgres:qwerty@spell-note-db:5432/postgres?sslmode=disable up
    depends_on:
      - spell-note-db
    volumes:
      - ./schema:/migrations
    networks:
      - app-network

  backend:
    build: .
    container_name: spell-note-backend
    environment:
      - DB_SERVER=spell-note-db
    ports:
      - "8000:8000"
    networks:
      - app-network
    depends_on:
      - spell-note-db
networks:
  app-network:
    driver: bridge